name: gradle-build-main

on:
  push:
    branches: feature-issue_156-gradle_ci

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      -
        name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      -
        name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.1.1
          arguments: build
